apiVersion: apps/v1
kind: Deployment
metadata:
  name: tserver-mconnect
spec:
  replicas: 4
  selector:
    matchLabels:
      app: tserver-mconnect
  template:
    metadata:
      labels:
        app: tserver-mconnect
    spec:
      containers:
      - name: tserver-mconnect
        image: docker.io/uablrek/tserver:latest
        imagePullPolicy: IfNotPresent
#        securityContext:
#          privileged: true
        env:
        - name: SERVERS
          value: "mconnect"
        ports:
        - name: mconnect
          containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: tserver-mconnect
spec:
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv6
  selector:
    app: tserver-mconnect
  type: LoadBalancer
#  allocateLoadBalancerNodePorts: false
  ports:
  - port: 5001
    name: mconnect
