apiVersion: v1
kind: Service
metadata:
  name: etp-local
spec:
  ipFamilyPolicy: RequireDualStack
  selector:
    app: tserver-daemonset
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  externalTrafficPolicy: Local
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
  - port: 8080
    name: kahttp
  - port: 8443
    name: kahttps
  - port: 5004
    name: nc
