apiVersion: v1
kind: Service
metadata:
  name: kahttp-np
spec:
  ipFamilyPolicy: RequireDualStack
  selector:
    app: tserver
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 8080
    name: kahttp
