apiVersion: v1
kind: Service
metadata:
  name: alpine
spec:
  loadBalancerSourceRanges:
  - "192.168.2.0/24"
  - "fd00::c0a8:200/120"
#  - "192.168.1.0/24"
#  - "fd00::c0a8:100/120"
  ipFamilyPolicy: RequireDualStack
  selector:
    app: alpine
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  ports:
  - port: 7001
    name: nc
    targetPort: 7007
