apiVersion: v1
kind: Service
metadata:
  name: tserver
spec:
  ipFamilyPolicy: RequireDualStack
  selector:
    app: tserver
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
  - port: 80
    name: http
  - port: 8080
    name: kahttp
  - port: 8443
    name: kahttps
---
apiVersion: v1
kind: Service
metadata:
  name: tserver-udp
spec:
  ipFamilyPolicy: RequireDualStack
  selector:
    app: tserver
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  ports:
  - port: 5001
    protocol: UDP
    name: mconnect
  - port: 5003
    name: ctraffic
    protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: tserver-sctp
spec:
  ipFamilyPolicy: RequireDualStack
  selector:
    app: tserver
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  ports:
  - port: 6000
    protocol: SCTP
    name: sctpt
