apiVersion: v1
kind: Service
metadata:
  name: tserver
spec:
  ipFamilyPolicy: RequireDualStack
  selector:
    app: tserver
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  ports:
  - port: 5001
    name: mconnect
